title: WxCC Technical Partner Summit
description: Lab guide repository for the 2021 Cisco Webex Contact Center Technical Partner Summit
author:
  name: Lab support email
  email: 'techsummit@email.carehybrid.com'
remote_theme: jekyll/minima

minima:
  skin: dark
  social_links:
    twitter: Webex

header_pages:
  - HomePage.md
