title: WxCC Technical Partner Summit
description: Lab guide repository for the 2022
author:
  name: Lab support email
  email: 'wxcclabs@cisco.com'
remote_theme: jekyll/minima

minima:
  skin: dark
  social_links:
    twitter: Webex

header_pages:
  
