name: test automation

on:
  push:
    branches: [ master ]

jobs:

  Deploy:
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v2
      
      #Step 1: Login/SSH to EC2
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_SECRET  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USERNAME  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /opt/cicd
            echo "Hello World"
          '
